### ISSUE TITLE
Excercise 2 Task 5 step 23 fails with old Cloud Shell with Helm 2.6.x

### ISSUE THREAD

**Issue by aautere** [microsoft/MCW-Cloud-native-applications#143]
Do you have any instructions how to bypass a problem when executing 
`helm install web ./web`
 I complains about Tiller. When I checked my helm version it is something 2.6.x. I understand the instructions are for Helm 3 which does not contain Tiller. Can you instruct ho to bypass this problem? Should I try to update my Cloud Shell Helm to version 3 (if yes how?) or is there other way to executing the helm install command?

**Comment by vraposo** [comment]
There was an accidental downgrade in the Helm version with the latest Azure Cloud Shell update which will be fixed in the next update (show be Really Soon).

In the interim, it is possible to install Helm v3 yourself with `curl https://aka.ms/cloud-shell-helm3 | bash`.

Public Reference: https://twitter.com/snuffling/status/1230873689937235968

**Comment by aautere** [comment]
Thank you for the Helm 3 upgrade script, it solved the issue and saved a lot of my time 💗.
