### ISSUE TITLE
Error @ Exercise 2/Task 4/Step 23: Deploy a service using Helm chart

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Cloud-native-applications#204]
rajred@Azure:~/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web/charts$ **helm install web ./web**
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "web" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "web"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

rajred@Azure:~/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web/charts$ **helm version**
version.BuildInfo{Version:"**v3.3.0**-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}

not sure it is related to helm version 3.3 requirements?

**Comment by saimachi** [comment]
Hello @rajredd,

The issue that you are experiencing is not related to the helm version, since we were unable to isolate the same issue even though we used the same build of helm.

First, ensure that you delete the web deployment and the web service in Kubernetes dashboard, as described in Steps 1-4. If you tried making an update to the release using helm, consult the helm upgrade command (https://helm.sh/docs/helm/helm_upgrade/).

**Comment by rajredd** [comment]
OK, Thanks.
